import { Box, Grid, Flex, Link, Divider, Container } from 'theme-ui'
import { Row, Column, Layout } from '../components'

const Novel = () => {
	return (
		<Layout route='/novel'>
			<Row sx={{ mt: [8] }}>
				<Column
					start={[1, 1, 1, 1]}
					width={[5, 4, 3, 3]}
					sx={{ fontSize: [4, 5, 5, 7] }}
				>
					<Box
						sx={{
							textTransform: 'uppercase',
							mb: [5],
							fontStyle: 'italic',
							letterSpacing: '0.05em',
						}}
					>
						Planes
					</Box>
					<Box>
						An urgent, fiercely intelligent debut novel that goes deep inside
						the daily lives of two women—one in Rome, the other in North
						Carolina—to tell a story about the powerful interconnections, both
						personal and political, that exist beneath the surface of our world.
						{' '}<Link href='/'>Pre-order now</Link>.
					</Box>
				</Column>
			</Row>
			<Row>
			<Column start={1} width={3} sx={{mt: [10], fontSize: [4, 5, 5, 7]}}>
				What others are saying
			</Column>
			</Row>
			<Row sx={{ mt: [4] }}>
				<Column
					start={[1, 1, 1, 1]}
					width={[6, 2, 2, 2]}
					sx={{ fontSize: [3, 3, 3, 5] }}
				>
					<Box sx={{ fontSize: [10], mb: [-7] }}>“</Box>
					Peter Baker is that rare confident novelist with the most delicate
					touch. With his twin dramas unfolding on separate planes in Rome and
					in North Carolina, he shows us that the invisible network connecting
					everyone can be just as much impersonal actions taken by Washington as
					intimate domestic secrets that go unshared. Baker has the eye of a
					seasoned journalist and the ear of a poet; I can’t wait to be absorbed
					in whatever he writes next.
					<Box
						sx={{
							mt: [3],
							fontSize: [2, 2, 2, 3],
							letterSpacing: '0.05em',
							fontStyle: 'italic',
							textTransform: 'uppercase',
						}}
					>
						— Sandi Tan
					</Box>
				</Column>
				<Column
					start={[1, 3, 3, 3]}
					width={[6, 2, 2, 2]}
					sx={{ fontSize: [3, 3, 3, 5] }}
				>
					<Box sx={{ fontSize: [10], mb: [-7] }}>“</Box>
					How do you come home from an atrocity? Peter C. Baker’s absorbing,
					closely observed novel follows two couples, an ocean apart—one wounded
					by a war crime, the other just starting to reckon with being
					implicated in it—as they try to find a way to live in the aftermath.
					Baker’s offbeat, suggestive strategy is to let the stories intertwine,
					so that subtle resonances emerge: variations on the themes of
					patience, misdirection, forgiveness, and exasperation that play in
					every marriage. Planes is an insightful book about the slow, zigzag
					work of healing that nonetheless moves at the speed of a thriller.
					<Box
						sx={{
							mt: [3],
							fontSize: [2, 2, 2, 3],
							letterSpacing: '0.05em',
							fontStyle: 'italic',
							textTransform: 'uppercase',
						}}
					>
						— Caleb Crain
					</Box>
				</Column>
				<Column
					start={[1, 5, 5, 5]}
					width={[6, 2, 2, 2]}
					sx={{ fontSize: [3, 3, 3, 5] }}
				>
					<Box sx={{ fontSize: [10], mb: [-7] }}>“</Box>
					This novel stunned me with its gravity and its wisdom, its sense of
					life’s turbulence and mystery. Baker is an absolutely brilliant
					writer—in league with Ferrante and DeLillo—with a deep understanding
					of the interwoven, interconnected web that holds the entire world in
					its grasp. He also has a novelist’s eye for the moment at hand, how it
					spreads and fills with love and stops time. I was reminded again that
					all our great novels are about human decisions. In this book,
					stretching from Rome to the suburban meeting rooms of a North Carolina
					school board, an almost unbearable suspense is generated by incredibly
					good and incredibly bad decisions. In Baker’s hands, an endlessly
					interesting, somewhat treacherous truth emerges; we are implicated in
					each other’s lives, and all drink from the same rich and complex well.
					<Box
						sx={{
							mt: [3],
							fontSize: [2, 2, 2, 3],
							letterSpacing: '0.05em',
							fontStyle: 'italic',
							textTransform: 'uppercase',
						}}
					>
						— Rebecca Lee
					</Box>
				</Column>
			</Row>
		</Layout>
	)
}

export default Novel
